export const PERMISSIONS = {
  VIEW_USERS: "ver_usuarios",
  CREATE_USER: "crear_usuario",
  UPDATE_USER: "modificar_usuario",
  DELETE_USER: "eliminar_usuario",
  CHANGE_USER_PASSWORD: "cambiar_contrasena_usuario",
  VIEW_PERMISSIONS: "ver_permisos",
  ASSIGN_PERMISSION: "asignar_permiso_a_usuario",
  REMOVE_PERMISSION: "quitar_permiso_a_usuario",
  VIEW_PROVEEDORES: "ver_proveedor",
  CREATE_PROVEEDOR: "crear_proveedor",
  UPDATE_PROVEEDOR: "modificar_proveedor",
  DELETE_PROVEEDOR: "eliminar_proveedor",
  VIEW_CLIENTES: "ver_clientes",
  CREATE_CLIENTE: "crear_cliente",
  UPDATE_CLIENTE: "modificar_cliente",
  DELETE_CLIENTE: "eliminar_cliente",
  VIEW_CATEGORIAS: "ver_categorias",
  CREATE_CATEGORIA: "crear_categorias",
  UPDATE_CATEGORIA: "modificar_categorias",
  DELETE_CATEGORIA: "eliminar_categorias",
  VIEW_SUB_CATEGORIAS: "ver_sub_categorias",
  CREATE_SUB_CATEGORIA: "crear_sub_categorias",
  UPDATE_SUB_CATEGORIA: "modificar_sub_categorias",
  DELETE_SUB_CATEGORIA: "eliminar_sub_categorias",
  VIEW_ARTICULOS: "ver_articulos",
  CREATE_ARTICULO: "crear_articulos",
  UPDATE_ARTICULO: "modificar_articulos",
  DELETE_ARTICULO: "eliminar_articulos",
  VIEW_STOCK: "ver_stock",
  CREATE_STOCK: "crear_stock",
  UPDATE_STOCK: "modificar_stock",
  DELETE_STOCK: "eliminar_stock",
  VIEW_VENTAS: "ver_ventas",
  CREATE_VENTA: "crear_venta",
  ANULAR_VENTA: "anular_venta",
  VENDER_SIN_STOCK: "vender_sin_stock",
  GENERAR_PRESUPUESTO: "generar_presupuesto",
  VIEW_TIPOS_VENTA: "ver_tipos_venta",
  CREATE_TIPO_VENTA: "crear_tipo_venta",
  UPDATE_TIPO_VENTA: "modificar_tipo_venta",
  DELETE_TIPO_VENTA: "eliminar_tipo_venta",
  VIEW_AUDITORIA: "ver_auditoria",
  VIEW_CIERRES: "ver_cierres",
  CREATE_CIERRE: "crear_cierre",
  REABRIR_CIERRE: "reabrir_cierre",
  VIEW_DOLAR: "ver_dolar",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionValue = (typeof PERMISSIONS)[PermissionKey];
