use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionCode {
    ViewUsers,
    CreateUser,
    UpdateUser,
    DeleteUser,
    ChangeUserPassword,
    ViewPermissions,
    AssignPermission,
    RemovePermission,
    ViewProveedores,
    CreateProveedor,
    UpdateProveedor,
    DeleteProveedor,
    ViewCategorias,
    CreateCategoria,
    UpdateCategoria,
    DeleteCategoria,
    ViewSubCategorias,
    CreateSubCategoria,
    UpdateSubCategoria,
    DeleteSubCategoria,
    ViewArticulos,
    CreateArticulo,
    UpdateArticulo,
    DeleteArticulo,
    ViewStock,
    CreateStock,
    UpdateStock,
    DeleteStock,
    ViewVentas,
    CreateVenta,
    AnularVenta,
    VenderSinStock,
    GenerarPresupuesto,
    ViewTiposVenta,
    CreateTipoVenta,
    UpdateTipoVenta,
    DeleteTipoVenta,
    ViewAuditoria,
    ViewCierres,
    CreateCierre,
    ReopenCierre,
}

impl PermissionCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            PermissionCode::ViewUsers => "ver_usuarios",
            PermissionCode::CreateUser => "crear_usuario",
            PermissionCode::UpdateUser => "modificar_usuario",
            PermissionCode::DeleteUser => "eliminar_usuario",
            PermissionCode::ChangeUserPassword => "cambiar_contrasena_usuario",
            PermissionCode::ViewPermissions => "ver_permisos",
            PermissionCode::AssignPermission => "asignar_permiso_a_usuario",
            PermissionCode::RemovePermission => "quitar_permiso_a_usuario",
            PermissionCode::ViewProveedores => "ver_proveedor",
            PermissionCode::CreateProveedor => "crear_proveedor",
            PermissionCode::UpdateProveedor => "modificar_proveedor",
            PermissionCode::DeleteProveedor => "eliminar_proveedor",
            PermissionCode::ViewCategorias => "ver_categorias",
            PermissionCode::CreateCategoria => "crear_categorias",
            PermissionCode::UpdateCategoria => "modificar_categorias",
            PermissionCode::DeleteCategoria => "eliminar_categorias",
            PermissionCode::ViewSubCategorias => "ver_sub_categorias",
            PermissionCode::CreateSubCategoria => "crear_sub_categorias",
            PermissionCode::UpdateSubCategoria => "modificar_sub_categorias",
            PermissionCode::DeleteSubCategoria => "eliminar_sub_categorias",
            PermissionCode::ViewArticulos => "ver_articulos",
            PermissionCode::CreateArticulo => "crear_articulos",
            PermissionCode::UpdateArticulo => "modificar_articulos",
            PermissionCode::DeleteArticulo => "eliminar_articulos",
            PermissionCode::ViewStock => "ver_stock",
            PermissionCode::CreateStock => "crear_stock",
            PermissionCode::UpdateStock => "modificar_stock",
            PermissionCode::DeleteStock => "eliminar_stock",
            PermissionCode::ViewVentas => "ver_ventas",
            PermissionCode::CreateVenta => "crear_venta",
            PermissionCode::AnularVenta => "anular_venta",
            PermissionCode::VenderSinStock => "vender_sin_stock",
            PermissionCode::GenerarPresupuesto => "generar_presupuesto",
            PermissionCode::ViewTiposVenta => "ver_tipos_venta",
            PermissionCode::CreateTipoVenta => "crear_tipo_venta",
            PermissionCode::UpdateTipoVenta => "modificar_tipo_venta",
            PermissionCode::DeleteTipoVenta => "eliminar_tipo_venta",
            PermissionCode::ViewAuditoria => "ver_auditoria",
            PermissionCode::ViewCierres => "ver_cierres",
            PermissionCode::CreateCierre => "crear_cierre",
            PermissionCode::ReopenCierre => "reabrir_cierre",
        }
    }

    pub fn all() -> Vec<PermissionCode> {
        vec![
            PermissionCode::ViewUsers,
            PermissionCode::CreateUser,
            PermissionCode::UpdateUser,
            PermissionCode::DeleteUser,
            PermissionCode::ChangeUserPassword,
            PermissionCode::ViewPermissions,
            PermissionCode::AssignPermission,
            PermissionCode::RemovePermission,
            PermissionCode::ViewProveedores,
            PermissionCode::CreateProveedor,
            PermissionCode::UpdateProveedor,
            PermissionCode::DeleteProveedor,
            PermissionCode::ViewCategorias,
            PermissionCode::CreateCategoria,
            PermissionCode::UpdateCategoria,
            PermissionCode::DeleteCategoria,
            PermissionCode::ViewSubCategorias,
            PermissionCode::CreateSubCategoria,
            PermissionCode::UpdateSubCategoria,
            PermissionCode::DeleteSubCategoria,
            PermissionCode::ViewArticulos,
            PermissionCode::CreateArticulo,
            PermissionCode::UpdateArticulo,
            PermissionCode::DeleteArticulo,
            PermissionCode::ViewStock,
            PermissionCode::CreateStock,
            PermissionCode::UpdateStock,
            PermissionCode::DeleteStock,
            PermissionCode::ViewVentas,
            PermissionCode::CreateVenta,
            PermissionCode::AnularVenta,
            PermissionCode::VenderSinStock,
            PermissionCode::GenerarPresupuesto,
            PermissionCode::ViewTiposVenta,
            PermissionCode::CreateTipoVenta,
            PermissionCode::UpdateTipoVenta,
            PermissionCode::DeleteTipoVenta,
            PermissionCode::ViewAuditoria,
            PermissionCode::ViewCierres,
            PermissionCode::CreateCierre,
            PermissionCode::ReopenCierre,
        ]
    }
}
